HANDLER(GET_ANGLES, cnc_handler__send_angles)
HANDLER(SET_MOTORS_SPEED, cnc_handler__set_motors_speed)
HANDLER(GET_PID, cnc_handler__get_pid)
HANDLER(SET_PID, cnc_handler__set_pid)
HANDLER(RECEIVER_STATE, cnc_handler__set_receiver_state)
HANDLER(KEEP_ALIVE, main__keep_alive)
